/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.isw.concesionario.view;

import com.isw.concesionario.menu.Controller;
import com.isw.concesionario.menu.ControllerAdministrativo;
import com.isw.concesionario.menu.ControllerEmpleado;
import com.isw.concesionario.menu.Login;
import com.isw.concesionario.model.Concesionario;
import com.isw.concesionario.service.ServicioAdministrativo;
import com.isw.concesionario.service.ServicioConcesionario;
import com.isw.concesionario.service.ServicioDetalleFactura;
import com.isw.concesionario.service.ServicioEmpleado;
import com.isw.concesionario.service.ServicioFactura;
import com.isw.concesionario.service.ServicioVehiculo;
import javax.swing.JOptionPane;

/**
 *
 * @author Juan
 */
public class GUIPrincipal extends javax.swing.JFrame {

    private ServicioEmpleado servicioEmpleado;
        private ServicioAdministrativo servicioAdministrativo;
        private ServicioConcesionario servicioConcesionario;
        private ServicioVehiculo servicioVehiculo;
        private ServicioDetalleFactura servicioDetalleFactura;
        private ServicioFactura servicioFactura;
        
        private Controller controller;
        Login login;
    
    /**
     * Creates new form GUIPrincipal
     */
    public GUIPrincipal() {
        initComponents();
        
        servicioEmpleado = new ServicioEmpleado(); 
        servicioAdministrativo = new ServicioAdministrativo();
        servicioConcesionario = new ServicioConcesionario();
        servicioVehiculo = new ServicioVehiculo();
        servicioDetalleFactura = new ServicioDetalleFactura(servicioVehiculo);
        servicioFactura = new ServicioFactura();
        
        login = new Login(servicioEmpleado, servicioAdministrativo, servicioConcesionario,
        servicioVehiculo, servicioDetalleFactura, servicioFactura);
        
        Concesionario conce = new Concesionario("algo", "otra cosa", "nose", "el ultimo");
        servicioAdministrativo.crearAdministrativo("111", "123", "pedro", "pascal", "Jordan", "pedro.com", "2", "3", conce);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnIngresar = new javax.swing.JButton();
        txtUsuario = new javax.swing.JTextField();
        txtContrasenia = new javax.swing.JTextField();
        lblUsuario = new javax.swing.JLabel();
        lblContrasenia = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnIngresar.setText("Ingresar");
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });

        lblUsuario.setText("Usuario");

        lblContrasenia.setText("Contraseña");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblContrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtContrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnIngresar))
                .addContainerGap(168, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(59, Short.MAX_VALUE)
                .addComponent(lblUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblContrasenia)
                .addGap(15, 15, 15)
                .addComponent(txtContrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(btnIngresar)
                .addGap(60, 60, 60))
        );

        btnIngresar.getAccessibleContext().setAccessibleName("btnIngresar");
        txtUsuario.getAccessibleContext().setAccessibleName("");
        txtContrasenia.getAccessibleContext().setAccessibleName("lblContrasenia");
        lblUsuario.getAccessibleContext().setAccessibleName("txtUsuario");
        lblContrasenia.getAccessibleContext().setAccessibleName("lblContrasenia");

        getAccessibleContext().setAccessibleName("lblUsuario");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        // TODO add your handling code here:
        controller = login.login(txtUsuario.getText(), txtContrasenia.getText());
        if(controller instanceof ControllerAdministrativo)
        {
            JOptionPane.showMessageDialog(null, "Holi", "Titulo", JOptionPane.INFORMATION_MESSAGE);
        }
        else if(controller instanceof ControllerEmpleado)
        {
            
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Intente nuevamente", "Contraseña incorrecta", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnIngresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIngresar;
    private javax.swing.JLabel lblContrasenia;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JTextField txtContrasenia;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
